import { fn } from "storybook/test";
import { useArgs } from "storybook/internal/preview-api";
import { Grid } from "./Grid";

export default {
  title: "Components/Grid",
  component: Grid,
  argTypes: {
    cars: { control: "object" },
  },
};

export const Default = {
  args: {
    cars: [
      {
        id: "bmw-m3-1",
        favourit: false,
        onFavourit: () => {},
        name: "BMW M3",
        type: "Sport",
        image: "/src/assets/CarSportBMW.png",
        fuelCapacity: 90,
        gearbox: "Automat",
        numberOfSeats: 4,
        price: 90.0,
        onRent: fn,
      },
      {
        id: "koenigsegg-1",
        favourit: false,
        onFavourit: () => {},
        name: "Koenigsegg",
        type: "Sport",
        image: "/src/assets/CarSportKG.png",
        fuelCapacity: 90,
        gearbox: "Automat",
        numberOfSeats: 2,
        price: 100.0,
        onRent: fn,
      },
      {
        id: "nissan-gt-r-1",
        favourit: false,
        onFavourit: () => {},
        name: "Nissan GT - R",
        type: "Sport",
        image: "/src/assets/CarSportGT-R.png",
        fuelCapacity: 80,
        gearbox: "Automat",
        numberOfSeats: 2,
        price: 89.0,
        onRent: fn,
      },
      {
        id: "rolls-royce-1",
        favourit: false,
        onFavourit: () => {},
        name: "Rolls - Royce",
        type: "Sport",
        image: "/src/assets/CarSportRR.png",
        fuelCapacity: 70,
        gearbox: "Automat",
        numberOfSeats: 4,
        price: 100.0,
        onRent: fn,
      },
      {
        id: "rush-1",
        favourit: false,
        onFavourit: () => {},
        name: "All New Rush",
        type: "SUV",
        image: "/src/assets/CarSuvRush.png",
        fuelCapacity: 70,
        gearbox: "Manual",
        numberOfSeats: 6,
        price: 72.0,
        onRent: fn,
      },
      {
        id: "mg-zx-1",
        favourit: false,
        onFavourit: () => {},
        name: "MG ZX Exclusice",
        type: "Hatchback",
        image: "/src/assets/CarSuvMG-ZX.png",
        fuelCapacity: 70,
        gearbox: "Manual",
        numberOfSeats: 4,
        price: 69.99,
        onRent: fn,
      },
      {
        id: "cr-v-1",
        favourit: false,
        onFavourit: () => {},
        name: "CR-V",
        type: "SUV",
        image: "/src/assets/CarSuvCR-Vblack.png",
        fuelCapacity: 80,
        gearbox: "Manual",
        numberOfSeats: 6,
        price: 80.0,
        onRent: fn,
      },
      {
        id: "mg-zs-1",
        favourit: false,
        onFavourit: () => {},
        name: "New MG ZS",
        type: "SUV",
        image: "/src/assets/CarSuvMG-ZS.png",
        fuelCapacity: 70,
        gearbox: "Manual",
        numberOfSeats: 6,
        price: 80.0,
        onRent: fn,
      },
    ],
  },
};
