export const CitySelect = [
  { value: "WAW", label: "Warszawa" },
  { value: "KRK", label: "Kraków" },
  { value: "LDZ", label: "Łódź" },
  { value: "WRO", label: "Wrocław" },
  { value: "POZ", label: "Poznań" },
  { value: "GDG", label: "Gdańsk" },
  { value: "SZC", label: "Szczecin" },
  { value: "BYD", label: "Bydgoszcz" },
  { value: "LUB", label: "Lublin" },
  { value: "BIA", label: "Białystok" },
  { value: "KAT", label: "Katowice" },
  { value: "GYN", label: "Gdynia" },
  { value: "CZE", label: "Częstochowa" },
  { value: "RAD", label: "Radom" },
  { value: "SOS", label: "Sosnowiec" },
  { value: "TOR", label: "Toruń" },
  { value: "KIE", label: "Kielce" },
  { value: "RZE", label: "Rzeszów" },
  { value: "OPL", label: "Opole" },
  { value: "ELB", label: "Elbląg" },
  { value: "GLI", label: "Gliwice" },
  { value: "ZAB", label: "Zabrze" },
  { value: "BYT", label: "Bytom" },
  { value: "OLS", label: "Olsztyn" },
  { value: "TAR", label: "Tarnów" },
  { value: "PLK", label: "Płock" },
  { value: "GOR", label: "Gorzów Wielkopolski" },
  { value: "ZIE", label: "Zielona Góra" },
];
